In [3]:
import numpy as np
# we import the numpy liberary to our notebook

In [4]:
np.__version__

'1.13.1'

In [5]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
# make matrix of size 4 x 4
d = np.array(
[ [1,2,3,4],
  [2,3,4,5],
  [3,4,5,6],
  [4,5,6,7]
]
)
print(d,'\n',d.shape)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]] 
 (4, 4)


In [8]:
a = np.zeros((3,4))
print(a)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [9]:
b = np.ones((3,4))
print(b)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [10]:
e = np.full((4,4),5.)
print(e)


[[ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]
 [ 5.  5.  5.  5.]]


In [12]:
 r = np.random.random((3,3))
print(r)

[[ 0.0967643   0.90832949  0.6582792 ]
 [ 0.92209286  0.49121726  0.38749813]
 [ 0.20112461  0.14970975  0.34963414]]


In [13]:
for i in range(100):
    print(i)
    

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [14]:
d

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [17]:
d[0,1]


array([[1]])

In [19]:
# generate a identity matrix of 50 x 50 
i = np.eye(50,50)
print(i)

[[ 1.  0.  0. ...,  0.  0.  0.]
 [ 0.  1.  0. ...,  0.  0.  0.]
 [ 0.  0.  1. ...,  0.  0.  0.]
 ..., 
 [ 0.  0.  0. ...,  1.  0.  0.]
 [ 0.  0.  0. ...,  0.  1.  0.]
 [ 0.  0.  0. ...,  0.  0.  1.]]


In [23]:
# generate a random matrix of size 10 x 20
r = np.random.random((10,20))
print(r,'\nShape = ',r.shape)


[[ 0.18102639  0.76866311  0.68582739  0.5831867   0.12695419  0.21665906
   0.14115377  0.87739302  0.50788009  0.49249752  0.78698736  0.55509479
   0.03298402  0.18345749  0.95500475  0.12472377  0.10614877  0.74420602
   0.02394411  0.02694063]
 [ 0.63291097  0.83325861  0.09009602  0.24239781  0.19227194  0.24636141
   0.2793238   0.46783643  0.65015095  0.63501058  0.58287216  0.99277521
   0.95909801  0.00837529  0.87073025  0.46731035  0.73584478  0.32999601
   0.69715475  0.08303711]
 [ 0.41483517  0.92486368  0.56990131  0.18614826  0.72138894  0.68373982
   0.48651464  0.15493379  0.61189683  0.5689288   0.22654448  0.8431009
   0.35910306  0.89757592  0.56122667  0.32693524  0.44148818  0.47534198
   0.42777676  0.75420844]
 [ 0.64234729  0.15376319  0.69725143  0.57604027  0.77432248  0.93677097
   0.20881361  0.33090085  0.90138207  0.52434803  0.41605799  0.78803626
   0.68837568  0.1225403   0.75600655  0.16553406  0.47816697  0.21809759
   0.16164162  0.49456981]
 [ 0.

In [24]:
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
b

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [26]:
d

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

In [28]:
print(d[1])

[2 3 4 5]


In [31]:
bol = (d > 2)
print(bol)

[[False False  True  True]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [32]:
print(d[bol])

[3 4 3 4 5 3 4 5 6 4 5 6 7]


In [37]:
# create a matrix of 3 x 3 with random values 
td = np.array([
    [11,23,34],
    [32,44,12],
    [3,5,2]
])

In [35]:
print(th[th > 10])
print(th[th < 10])

[11 23 34 32 44 12]
[3 5 2]


In [36]:
print(np.sqrt(th))

[[ 3.31662479  4.79583152  5.83095189]
 [ 5.65685425  6.63324958  3.46410162]
 [ 1.73205081  2.23606798  1.41421356]]


In [41]:
#take two matrix of 2 x2 and appply matrix multiplication
aa = np.array([[2,2],[2,3]])
bb = np.array([[3,5],[4,5]])
print(aa.dot(bb))

[[14 20]
 [18 25]]


In [42]:
y = np.empty_like(td)
print(y)

[[16843009 16843009 16843009]
 [16843009 16843009 16843009]
 [16843009 16843009 16843009]]


In [43]:
print(td)

[[11 23 34]
 [32 44 12]
 [ 3  5  2]]


In [46]:
import pandas as pd
# create a dataframe of student names and students marks
data = pd.DataFrame({
    'Sr No':[1,2,3,4],
    'Name':['Adam','Ali','Moaz','Gohar'],
    'Marks':[50,34,90,43]
})

In [47]:
data

Marks   Name  Sr No
0     50   Adam      1
1     34    Ali      2
2     90   Moaz      3
3     43  Gohar      4